---
name: "Continue Watching"
guid: "7b3f1b70-4d0e-4d9d-a92d-5e2f632b91c1"
version: "1.0.1.0"
targetAbi: "10.11.11.0"
framework: "net9.0"
overview: "Continue Watching updates Jellyfin's default resume list to work like you expect it to"
description: >
  Updates Jellyfin's default resume list to work like you expect it to.
  Works with and without IAmParadox27's Home Screen Sections plugin.
  Supported by all clients.
category: "General"
owner: "timvu"
artifacts:
- "Jellyfin.Plugin.ContinueWatching.dll"
- "Jellyfin.Plugin.HomeScreenSections.Client.dll"
changelog: >
  Initial release
