name: "Continue Watching"
guid: "7b3f1b70-4d0e-4d9d-a92d-5e2f632b91c1"
version: "1.1.0.0"
targetAbi: "12.0.0.0"
framework: "net10.0"
overview: "Updates Continue Watching to work like you export"
description: >
  Updates the Continue Watching section to work like you expect it to.
  Works with and without the Home Screen Sections plugin.
  Supported by all clients.
category: "General"
owner: "timvu"
artifacts:
- "Jellyfin.Plugin.ContinueWatching.dll"
- "Jellyfin.Plugin.HomeScreenSections.Client.dll"
changelog: >
  Add support for Jellyfin v12.0-rc2
